# Parte 1

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/breast-cancer-dataset/breast-cancer.csv


In [2]:
df = pd.read_csv('/kaggle/input/breast-cancer-dataset/breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
df.shape

(569, 32)

In [4]:
df.diagnosis.value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [5]:
df['diagnosis_maligno'] = df.diagnosis.apply(lambda x: 1 if x == 'M' else 0)
df['diagnosis_maligno'].value_counts()

0    357
1    212
Name: diagnosis_maligno, dtype: int64

## Separando treino e teste:

In [6]:
from sklearn.model_selection import train_test_split

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [7]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'diagnosis_maligno'],
      dtype='object')

In [8]:
X = df[['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']]

y = df['diagnosis_maligno']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.1)

In [10]:
len(X_train)

460

In [11]:
len(X_test)

57

In [12]:
len(X_val)

52

## Normalizando os dados:

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_val = sc.fit_transform(X_val)

In [16]:
X_train

array([[ 1.61003947,  1.0693732 ,  1.6711173 , ...,  1.13460025,
         0.60775635,  0.58275091],
       [-0.10988902, -0.00668358, -0.17773989, ..., -0.52710841,
        -0.8794167 , -0.43356234],
       [ 0.08183161,  0.79453619,  0.13033594, ..., -0.09218466,
        -1.03479299, -0.21515847],
       ...,
       [-0.00986087,  0.08881063,  0.18825098, ...,  0.50771016,
        -0.81282686,  1.31857041],
       [ 0.12906712, -1.05479084,  0.0692034 , ...,  0.12677695,
         0.31444397, -0.11548788],
       [-0.68227233, -0.0765574 , -0.70943213, ..., -0.71262589,
        -0.59561715, -0.2211496 ]])

## Definição da arquitetura:

In [17]:
import tensorflow as tf
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

## Compilação:

In [18]:
def build_model():
    model = Sequential()
    model.add(Dense(input_dim = 30, units = 10, activation = 'relu'))
    model.add(Dense(10, activation = 'relu'))
    
    model.add(Dense(1, activation = 'sigmoid'))
    
    return model

In [19]:
model = build_model()

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                310       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 431
Trainable params: 431
Non-trainable params: 0
_________________________________________________________________


## Treinamento:

In [21]:
adam = Adam(lr = 0.01)
model.compile(loss = 'binary_crossentropy',
             optimizer = adam,
             metrics = ['accuracy'])

In [22]:
model.fit(x = X_train, y = y_train, validation_data = (X_val, y_val), batch_size = 16, epochs = 10)

Epoch 1/10
29/29 [==============================] - 1s 10ms/step - loss: 0.7488 - accuracy: 0.4522 - val_loss: 0.5543 - val_accuracy: 0.7115
Epoch 2/10
29/29 [==============================] - 0s 3ms/step - loss: 0.5318 - accuracy: 0.7870 - val_loss: 0.4285 - val_accuracy: 0.8846
Epoch 3/10
29/29 [==============================] - 0s 3ms/step - loss: 0.4094 - accuracy: 0.8652 - val_loss: 0.3514 - val_accuracy: 0.9038
Epoch 4/10
29/29 [==============================] - 0s 3ms/step - loss: 0.3203 - accuracy: 0.9109 - val_loss: 0.2991 - val_accuracy: 0.8846
Epoch 5/10
29/29 [==============================] - 0s 3ms/step - loss: 0.2581 - accuracy: 0.9152 - val_loss: 0.2644 - val_accuracy: 0.8654
Epoch 6/10
29/29 [==============================] - 0s 3ms/step - loss: 0.2151 - accuracy: 0.9239 - val_loss: 0.2388 - val_accuracy: 0.8654
Epoch 7/10
29/29 [==============================] - 0s 3ms/step - loss: 0.1856 - accuracy: 0.9370 - val_loss: 0.2185 - val_accuracy: 0.8846
Epoch 8/10
29/29 [=

## Avaliação:

In [23]:
y_pred = model.predict(X_test)

2/2 [==============================] - 0s 4ms/step


In [24]:
from sklearn.metrics import confusion_matrix

In [25]:
y_pred

array([[9.99645174e-01],
       [2.05478534e-01],
       [4.60204422e-01],
       [1.45396925e-05],
       [1.80416524e-01],
       [8.90251771e-02],
       [9.19978559e-01],
       [9.35261667e-01],
       [3.30858976e-01],
       [1.71013281e-01],
       [4.44173247e-01],
       [9.89045203e-01],
       [7.89982378e-02],
       [9.01023857e-04],
       [4.19139117e-03],
       [1.75436631e-01],
       [4.42351788e-01],
       [4.29838561e-02],
       [4.24084254e-03],
       [5.23228832e-02],
       [9.96854246e-01],
       [4.60849889e-02],
       [9.96050477e-01],
       [3.87460664e-02],
       [9.98794973e-01],
       [2.01993007e-02],
       [1.74286023e-01],
       [6.18895173e-01],
       [1.65637303e-02],
       [6.06294852e-05],
       [5.11982799e-01],
       [7.55391419e-01],
       [8.83459389e-01],
       [5.94410077e-02],
       [8.82945582e-03],
       [9.91633356e-01],
       [9.01193261e-01],
       [9.98297155e-01],
       [1.77173112e-02],
       [2.67132610e-01],


In [26]:
cm = confusion_matrix(y_test, y_pred > 0.5)
cm

array([[37,  5],
       [ 0, 15]])